#' Outbreaker2: disease outbreak reconstruction using epidemiological and genetic data
#'
#'
#' @export
#'
#' @aliases outbreaker
#'
#' @rdname outbreaker
#'
#' @author Thibaut Jombart (\email{t_jombart@@imperial_ac_uk})
#'
#' @references Jombart T, Cori A, Didelot X, Cauchemez S, Fraser C and Ferguson
#' N (2014).  Bayesian reconstruction of disease outbreaks by combining
#' epidemiologic and genomic data. PLoS Computational Biology.
#'
#' @seealso \code{\link{outbreaker_data}} to process input data, and \code{\link{create_config}} to process/set up parameters
#'
#' @param data a list of named items containing input data as returned by
#'     \code{\link{outbreaker_data}}
#' 
#' @param config a set of settings as returned by \code{\link{create_config}}
## #' @param loglike a set of log-likelihood functions as returned by \code{\link{create_loglike}}

#' @param priors a set of prior functions with enclosed parameters as returned
#'     by \code{\link{create_priors}}

## #' @param posteriors a set of posterior functions as returned by \code{\link{outbreaker_create_posteriors}}
## #' @param moves a set of movement functions stored in a named list as returned by \code{\link{outbreaker_create_moves}}
## #'
#' @seealso \code{\link{create_config}} to see default parameters / set parameters and \code{\link{outbreaker_data}} to process input data
#'
#' @examples
#'
#' ## get data
#' data(fake_outbreak)
#' dat <- fake_outbreak$dat
#' w <- fake_outbreak$w
#'
#' \dontrun{
#' ## run outbreaker
#' out <- outbreaker(data = list(dna = dat$dna, dates = dat$onset, w_dens = w),
#' config = list(n_iter = 2e4, sample_every = 200))
#' plot(out)
#' as.data.frame(out)
#'
#' ## run outbreaker, no DNA sequences
#' out2 <- outbreaker(data = list(dates = dat$onset, w_dens = w),
#' config = list(n_iter = 2e4, sample_every = 200))
#' plot(out2)
#' as.data.frame(out2)
#'
#' }
outbreaker <- function(data = outbreaker_data(),
                       config = create_config(),
                       priors = create_priors(config)) {

    ## CHECKS / PROCESS DATA ##
    data <- outbreaker_data(data = data)

    ## CHECK / PROCESS CONFIG ##
    config <- create_config(config, data = data)

    ## ADD CONVOLUTIONS TO DATA ##
    data <- add_convolutions(data = data, config = config)

    ## MAKE A LIST OF LIKELIHOOD, PRIOR AND POSTERIOR FUNCTIONS WITH ENCLOSED DATA ##
    loglike <- create_loglike(data)
    priors <- create_priors(config)
    posteriors <- create_posteriors(loglike, priors)

    ## CREATE AND INITIALIZE MCMC CHAIN ##
    temp <- outbreaker_create_mcmc(data = data, config = config)
    param_store <- temp$store
    param_current <- temp$current
    param_store <- outbreaker_init_mcmc(param_current, param_store, loglike, priors)


    ## We put all density functions in a single list 'densities'. This includes 3 lists, for:
    ## log-likelihood, priors, and posteriors. All functions have enclosed items so that only the
    ## 'param' argument is needed.

    densities <- list(loglike = loglike, priors = priors, posteriors = posteriors)

    ## here we create a list of function for moving parameters
    moves <- create_moves(config = config, densities = densities)



    ## MCMC ##

    ## preliminary run to detect imported cases this relies on a shorter run of the MCMC,
    ## then computing the average 'global influence' (-loglike) of each data point, identifying
    ## outliers (based on fixed threshold) and marking outliers down as 'imported cases'.

    temp <- outbreaker_find_imports(moves = moves,
                                    data = data,
                                    param_current = param_current,
                                    param_store = param_store,
                                    config = config,
                                    densities = densities)
    param_current <- temp$param_current
    param_store <- temp$param_store
    config <- temp$config

    ## perform mcmc
    ## procedure is the same as before, with some cases fixed as 'imported'
    param_store <- outbreaker_move(moves = moves,
                                   data = data,
                                   param_current = param_current,
                                   param_store = param_store,
                                   config = config,
                                   densities = densities)


    ## SHAPE RESULTS ##
    ## this takes the chains generated by 'outbreaker_move', stored as a list, and
    ## puts everything back together as a single data.frame; augmented data stored as vectors
    ## (e_g. 'alpha') become numbered columns of the data.frame (e_g. 'alpha.1', 'alpha.2' etc.)
    out <- outbreaker_mcmc_shape(param_store, data)

    return(out)
}

