#' Outbreaker2: disease outbreak reconstruction using epidemiological and genetic data
#'
#'
#' @export
#'
#' @aliases outbreaker
#'
#' @rdname outbreaker
#'
#' @author Thibaut Jombart (\email{t.jombart@@imperial.ac.uk})
#'
#' @references Jombart T, Cori A, Didelot X, Cauchemez S, Fraser C and Ferguson
#' N (2014).  Bayesian reconstruction of disease outbreaks by combining
#' epidemiologic and genomic data. PLoS Computational Biology.
#'
#' @seealso \code{\link{outbreaker.data}} to process input data, and \code{\link{outbreaker.config}} to process/set up parameters
#'
#' @param data a list of named items containing input data as returned by \code{\link{outbreaker.data}}
#' @param config a set of settings as returned by \code{\link{outbreaker.config}}
## #' @param loglike a set of log-likelihood functions as returned by \code{\link{create.loglike}}
## #' @param priors a set of prior functions as returned by \code{\link{outbreaker.create.priors}}
## #' @param posteriors a set of posterior functions as returned by \code{\link{outbreaker.create.posteriors}}
## #' @param moves a set of movement functions stored in a named list as returned by \code{\link{outbreaker.create.moves}}
## #'
#' @seealso \code{\link{outbreaker.config}} to see default parameters / set parameters and \code{\link{outbreaker.data}} to process input data
#'
#' @importFrom stats dexp rnorm runif
#'
#' @examples
#'
#' ## get data
#' data(fakeOutbreak)
#' dat <- fakeOutbreak$dat
#' w <- fakeOutbreak$w
#'
#' \dontrun{
#' ## run outbreaker
#' out <- outbreaker(data=list(dna=dat$dna, dates=dat$onset, w.dens=w),
#' config=list(n.iter=2e4, sample.every=200))
#' plot(out)
#' as.data.frame(out)
#'
#' ## run outbreaker, no DNA sequences
#' out2 <- outbreaker(data=list(dates=dat$onset, w.dens=w),
#' config=list(n.iter=2e4, sample.every=200))
#' plot(out2)
#' as.data.frame(out2)
#'
#' }
outbreaker <- function(data = outbreaker.data(),
                       config = outbreaker.config()
                       ){

    ## CHECKS / PROCESS DATA ##
    data <- outbreaker.data(data=data)

    ## CHECK / PROCESS CONFIG ##
    config <- outbreaker.config(data=data, config=config)

    ## ADD CONVOLUTIONS TO DATA ##
    data <- add.convolutions(data=data, config=config)

    ## MAKE A LIST OF LIKELIHOOD, PRIOR AND POSTERIOR FUNCTIONS WITH ENCLOSED DATA ##
    loglike <- create.loglike(data)
    priors <- create.priors(config)
    posteriors <- create.posteriors(loglike, priors)

    ## CREATE AND INITIALIZE MCMC CHAIN ##
    param <- outbreaker.create.mcmc(data=data, config=config)
    param <- outbreaker.init.mcmc(param=param, loglike=loglike, priors=priors)

    ## CREATE FAST RANDOM VARIABLE GENERATORS ##
    rand <- outbreaker.rand.vec(config)

    ## We put all density functions in a single list 'densities'; all functions have enclosed items
    ## so that only the 'param' argument is needed, which describes the current state of the system
    ## (it is a list including past retained, and current augmented data and parameters).
    ##
    ## Included funcitons are:
    ## - $loglike: log-likelihood functions with enclosed data
    ## - $priors: prior functions with enclosed parameters
    ## - $posteriors: posterior functions with enclosed loglike and parameter functions

    densities <- list(loglike=loglike, priors=priors, posteriors=posteriors)


    ## MCMC ##

    ## preliminary run to detect imported cases this relies on a shorter run of the MCMC,
    ## then computing the average 'global influence' (-loglike) of each data point, identifying
    ## outliers (based on fixed threshold) and marking outliers down as 'imported cases'.
    ##
    temp <- outbreaker.find.imports(moves=moves, data=data, param=param,
                    config=config, densities=densities, rand=rand)
    param <- temp$param
    config <- temp$config

    ## perform mcmc
    ## procedure is the same as before, with some cases fixed as 'imported'
    moves <- outbreaker.create.moves(config=config)
    param <- outbreaker.move(moves=moves, data=data, param=param,
                    config=config, densities=densities, rand=rand)


    ## SHAPE RESULTS ##
    ## this takes the chains generated by 'outbreaker.move', stored as a list, and
    ## puts everything back together as a single data.frame; augmented data stored as vectors
    ## (e.g. 'alpha') become numbered columns of the data.frame (e.g. 'alpha.1', 'alpha.2' etc.)
    param <- outbreaker.mcmc.shape(param=param, data=data)

    return(param)
}

