# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_are_possible_ancestors <- function(t_inf, i) {
    .Call('outbreaker2_cpp_are_possible_ancestors', PACKAGE = 'outbreaker2', t_inf, i)
}

cpp_sample1 <- function(x) {
    .Call('outbreaker2_cpp_sample1', PACKAGE = 'outbreaker2', x)
}

cpp_pick_possible_ancestor <- function(t_inf, i) {
    .Call('outbreaker2_cpp_pick_possible_ancestor', PACKAGE = 'outbreaker2', t_inf, i)
}

cpp_find_descendents <- function(alpha, i) {
    .Call('outbreaker2_cpp_find_descendents', PACKAGE = 'outbreaker2', alpha, i)
}

cpp_find_local_cases <- function(alpha, i) {
    .Call('outbreaker2_cpp_find_local_cases', PACKAGE = 'outbreaker2', alpha, i)
}

cpp_swap_cases <- function(param, i) {
    .Call('outbreaker2_cpp_swap_cases', PACKAGE = 'outbreaker2', param, i)
}

cpp_ll_genetic <- function(data, param, i = NULL, custom_function = NULL) {
    .Call('outbreaker2_cpp_ll_genetic', PACKAGE = 'outbreaker2', data, param, i, custom_function)
}

cpp_ll_timing_infections <- function(data, param, i = NULL, custom_function = NULL) {
    .Call('outbreaker2_cpp_ll_timing_infections', PACKAGE = 'outbreaker2', data, param, i, custom_function)
}

cpp_ll_timing_sampling <- function(data, param, i = NULL, custom_function = NULL) {
    .Call('outbreaker2_cpp_ll_timing_sampling', PACKAGE = 'outbreaker2', data, param, i, custom_function)
}

cpp_ll_reporting <- function(data, param, i = NULL, custom_function = NULL) {
    .Call('outbreaker2_cpp_ll_reporting', PACKAGE = 'outbreaker2', data, param, i, custom_function)
}

cpp_ll_timing <- function(data, param, i = NULL, custom_functions = NULL) {
    .Call('outbreaker2_cpp_ll_timing', PACKAGE = 'outbreaker2', data, param, i, custom_functions)
}

cpp_ll_all <- function(data, param, i = NULL, custom_functions = NULL) {
    .Call('outbreaker2_cpp_ll_all', PACKAGE = 'outbreaker2', data, param, i, custom_functions)
}

cpp_move_mu <- function(data, param, config, custom_ll = NULL, custom_prior = NULL) {
    .Call('outbreaker2_cpp_move_mu', PACKAGE = 'outbreaker2', data, param, config, custom_ll, custom_prior)
}

cpp_move_pi <- function(data, param, config, custom_ll = NULL, custom_prior = NULL) {
    .Call('outbreaker2_cpp_move_pi', PACKAGE = 'outbreaker2', data, param, config, custom_ll, custom_prior)
}

cpp_move_t_inf <- function(data, param, list_custom_ll = NULL) {
    .Call('outbreaker2_cpp_move_t_inf', PACKAGE = 'outbreaker2', data, param, list_custom_ll)
}

cpp_move_alpha <- function(data, param, list_custom_ll = NULL) {
    .Call('outbreaker2_cpp_move_alpha', PACKAGE = 'outbreaker2', data, param, list_custom_ll)
}

cpp_move_swap_cases <- function(data, param, list_custom_ll = NULL) {
    .Call('outbreaker2_cpp_move_swap_cases', PACKAGE = 'outbreaker2', data, param, list_custom_ll)
}

cpp_move_kappa <- function(data, param, config, list_custom_ll = NULL) {
    .Call('outbreaker2_cpp_move_kappa', PACKAGE = 'outbreaker2', data, param, config, list_custom_ll)
}

cpp_prior_mu <- function(param, config, custom_function = NULL) {
    .Call('outbreaker2_cpp_prior_mu', PACKAGE = 'outbreaker2', param, config, custom_function)
}

cpp_prior_pi <- function(param, config, custom_function = NULL) {
    .Call('outbreaker2_cpp_prior_pi', PACKAGE = 'outbreaker2', param, config, custom_function)
}

cpp_prior_all <- function(param, config, custom_functions = NULL) {
    .Call('outbreaker2_cpp_prior_all', PACKAGE = 'outbreaker2', param, config, custom_functions)
}

