# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_are_possible_ancestors <- function(t_inf, i) {
    .Call(`_outbreaker2_cpp_are_possible_ancestors`, t_inf, i)
}

cpp_sample1 <- function(x) {
    .Call(`_outbreaker2_cpp_sample1`, x)
}

cpp_pick_possible_ancestor <- function(t_inf, i) {
    .Call(`_outbreaker2_cpp_pick_possible_ancestor`, t_inf, i)
}

cpp_find_descendents <- function(alpha, i) {
    .Call(`_outbreaker2_cpp_find_descendents`, alpha, i)
}

cpp_find_local_cases <- function(alpha, i) {
    .Call(`_outbreaker2_cpp_find_local_cases`, alpha, i)
}

cpp_swap_cases <- function(param, i, swap_place) {
    .Call(`_outbreaker2_cpp_swap_cases`, param, i, swap_place)
}

cpp_get_n_mutations <- function(data, i, j) {
    .Call(`_outbreaker2_cpp_get_n_mutations`, data, i, j)
}

cpp_lookup_sequenced_ancestor <- function(data, param, i) {
    .Call(`_outbreaker2_cpp_lookup_sequenced_ancestor`, data, param, i)
}

is_between_place <- function(place_matrix, t_inf, t_onw, alpha, C_ind, j) {
    .Call(`_outbreaker2_is_between_place`, place_matrix, t_inf, t_onw, alpha, C_ind, j)
}

get_transition_mat <- function(p_trans, p_place, p_place_adj, eps, tau, prop_place_unobserved, max_kappa) {
    .Call(`_outbreaker2_get_transition_mat`, p_trans, p_place, p_place_adj, eps, tau, prop_place_unobserved, max_kappa)
}

get_marginal_trans <- function(p_trans, p_place, p_place_adj) {
    .Call(`_outbreaker2_get_marginal_trans`, p_trans, p_place, p_place_adj)
}

t_inf_change <- function(data, alpha, kappa, p, t_inf_1, t_inf_2) {
    .Call(`_outbreaker2_t_inf_change`, data, alpha, kappa, p, t_inf_1, t_inf_2)
}

alpha_change <- function(data, p, kappa, t_inf, alpha_1, alpha_2) {
    .Call(`_outbreaker2_alpha_change`, data, p, kappa, t_inf, alpha_1, alpha_2)
}

local_n_contacts <- function(data, param, p) {
    .Call(`_outbreaker2_local_n_contacts`, data, param, p)
}

kappa_change <- function(data, param, p, t_inf, alpha, kappa1, kappa2) {
    .Call(`_outbreaker2_kappa_change`, data, param, p, t_inf, alpha, kappa1, kappa2)
}

swap_cases_change <- function(data, param, new_param, i, alpha, t_inf, kappa, local_cases, n_mat) {
    .Call(`_outbreaker2_swap_cases_change`, data, param, new_param, i, alpha, t_inf, kappa, local_cases, n_mat)
}

cpp_find_ancestors <- function(alpha, ancestors, i) {
    .Call(`_outbreaker2_cpp_find_ancestors`, alpha, ancestors, i)
}

cpp_find_mrca <- function(i, j, ancestors) {
    .Call(`_outbreaker2_cpp_find_mrca`, i, j, ancestors)
}

update_mrca <- function(combn, ancestors) {
    .Call(`_outbreaker2_update_mrca`, combn, ancestors)
}

cpp_ll_genetic <- function(data, param, i = NULL, custom_function = NULL) {
    .Call(`_outbreaker2_cpp_ll_genetic`, data, param, i, custom_function)
}

cpp_ll_timing_infections <- function(data, param, i = NULL, custom_function = NULL) {
    .Call(`_outbreaker2_cpp_ll_timing_infections`, data, param, i, custom_function)
}

cpp_ll_timing_sampling <- function(data, param, i = NULL, custom_function = NULL) {
    .Call(`_outbreaker2_cpp_ll_timing_sampling`, data, param, i, custom_function)
}

cpp_ll_reporting <- function(data, param, i = NULL, custom_function = NULL) {
    .Call(`_outbreaker2_cpp_ll_reporting`, data, param, i, custom_function)
}

cpp_ll_contact <- function(data, param, i = NULL, custom_function = NULL) {
    .Call(`_outbreaker2_cpp_ll_contact`, data, param, i, custom_function)
}

cpp_ll_timeline <- function(data, param, i = NULL, custom_function = NULL) {
    .Call(`_outbreaker2_cpp_ll_timeline`, data, param, i, custom_function)
}

cpp_ll_timing <- function(data, param, i = NULL, custom_functions = NULL) {
    .Call(`_outbreaker2_cpp_ll_timing`, data, param, i, custom_functions)
}

cpp_ll_all <- function(data, param, i = NULL, custom_functions = NULL) {
    .Call(`_outbreaker2_cpp_ll_all`, data, param, i, custom_functions)
}

cpp_move_mu <- function(param, data, config, custom_ll = NULL, custom_prior = NULL) {
    .Call(`_outbreaker2_cpp_move_mu`, param, data, config, custom_ll, custom_prior)
}

cpp_move_pi <- function(param, data, config, custom_ll = NULL, custom_prior = NULL) {
    .Call(`_outbreaker2_cpp_move_pi`, param, data, config, custom_ll, custom_prior)
}

cpp_move_tau <- function(param, data, config, custom_ll = NULL, custom_prior = NULL) {
    .Call(`_outbreaker2_cpp_move_tau`, param, data, config, custom_ll, custom_prior)
}

cpp_move_eps <- function(param, data, config, list_custom_ll = NULL, custom_prior = NULL) {
    .Call(`_outbreaker2_cpp_move_eps`, param, data, config, list_custom_ll, custom_prior)
}

cpp_move_eta <- function(param, data, config, custom_ll = NULL, custom_prior = NULL) {
    .Call(`_outbreaker2_cpp_move_eta`, param, data, config, custom_ll, custom_prior)
}

cpp_move_lambda <- function(param, data, config, custom_ll = NULL, custom_prior = NULL) {
    .Call(`_outbreaker2_cpp_move_lambda`, param, data, config, custom_ll, custom_prior)
}

cpp_move_t_inf <- function(param, data, config, list_custom_ll = NULL) {
    .Call(`_outbreaker2_cpp_move_t_inf`, param, data, config, list_custom_ll)
}

cpp_move_alpha <- function(param, data, config, list_custom_ll = NULL) {
    .Call(`_outbreaker2_cpp_move_alpha`, param, data, config, list_custom_ll)
}

cpp_move_model <- function(param, data, config, list_custom_ll = NULL) {
    .Call(`_outbreaker2_cpp_move_model`, param, data, config, list_custom_ll)
}

cpp_move_joint <- function(param, data, config, list_custom_ll = NULL) {
    .Call(`_outbreaker2_cpp_move_joint`, param, data, config, list_custom_ll)
}

cpp_move_swap_cases <- function(param, data, config, list_custom_ll = NULL) {
    .Call(`_outbreaker2_cpp_move_swap_cases`, param, data, config, list_custom_ll)
}

cpp_move_kappa <- function(param, data, config, list_custom_ll = NULL) {
    .Call(`_outbreaker2_cpp_move_kappa`, param, data, config, list_custom_ll)
}

cpp_prior_mu <- function(param, config, custom_function = NULL) {
    .Call(`_outbreaker2_cpp_prior_mu`, param, config, custom_function)
}

cpp_prior_pi <- function(param, config, custom_function = NULL) {
    .Call(`_outbreaker2_cpp_prior_pi`, param, config, custom_function)
}

cpp_prior_tau <- function(param, config, custom_function = NULL) {
    .Call(`_outbreaker2_cpp_prior_tau`, param, config, custom_function)
}

cpp_prior_eps <- function(param, config, custom_function = NULL) {
    .Call(`_outbreaker2_cpp_prior_eps`, param, config, custom_function)
}

cpp_prior_eta <- function(param, config, custom_function = NULL) {
    .Call(`_outbreaker2_cpp_prior_eta`, param, config, custom_function)
}

cpp_prior_lambda <- function(param, config, custom_function = NULL) {
    .Call(`_outbreaker2_cpp_prior_lambda`, param, config, custom_function)
}

cpp_prior_all <- function(param, config, custom_functions = NULL) {
    .Call(`_outbreaker2_cpp_prior_all`, param, config, custom_functions)
}

