# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

copy_values <- function(a, b) {
    invisible(.Call('outbreaker2_copy_values', PACKAGE = 'outbreaker2', a, b))
}

cpp.are.possible.ancestors <- function(t_inf, i) {
    .Call('outbreaker2_cpp_are_possible_ancestors', PACKAGE = 'outbreaker2', t_inf, i)
}

cpp.sampl1 <- function(x) {
    .Call('outbreaker2_cpp_sample1', PACKAGE = 'outbreaker2', x)
}

cpp.ll.genetic <- function(data, param, i) {
    .Call('outbreaker2_cpp_ll_genetic', PACKAGE = 'outbreaker2', data, param, i)
}

cpp.ll.timing.infections <- function(data, param, i) {
    .Call('outbreaker2_cpp_ll_timing_infections', PACKAGE = 'outbreaker2', data, param, i)
}

cpp.ll.timing.sampling <- function(data, param, i) {
    .Call('outbreaker2_cpp_ll_timing_sampling', PACKAGE = 'outbreaker2', data, param, i)
}

cpp.ll.reporting <- function(data, param, i) {
    .Call('outbreaker2_cpp_ll_reporting', PACKAGE = 'outbreaker2', data, param, i)
}

cpp.ll.timing <- function(data, param, i) {
    .Call('outbreaker2_cpp_ll_timing', PACKAGE = 'outbreaker2', data, param, i)
}

cpp.ll.all <- function(data, param, i) {
    .Call('outbreaker2_cpp_ll_all', PACKAGE = 'outbreaker2', data, param, i)
}

cpp.move.mu <- function(data, param, config) {
    invisible(.Call('outbreaker2_cpp_move_mu', PACKAGE = 'outbreaker2', data, param, config))
}

cpp.move.t.inf <- function(data, param) {
    invisible(.Call('outbreaker2_cpp_move_t_inf', PACKAGE = 'outbreaker2', data, param))
}

